version: "3.9"
services:
  postgres-card:
    container_name: postgres-card
    image: postgres:alpine3.16
    environment:
      POSTGRES_DB: card-service
      POSTGRES_USER: mateuszuran
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-card:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped