server.port: 8181

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
spring:
  application.name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - DELETE
      routes:
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/card/**