server.port: 8181

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    preferIpAddress: true
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
spring:
  application.name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          audience: ptd
          issuer-uri: https://dev-ofaxacelbca8ndxy.eu.auth0.com/

  cloud:
    gateway:
      routes:
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/card/**, /api/trip/**, /api/fuel/**

        - id: pdf-service
          uri: lb://pdf-service
          predicates:
            - Path=/api/pdf/**
          filters:
            - ExtractUsername