server.port: 8181

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.security: TRACE
spring:
  application.name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/ptd-lite

  cloud:
    gateway:
      routes:
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/card/**, /api/trip/**, /api/fuel/**

        - id: pdf-service
          uri: lb://pdf-service
          predicates:
            - Path=/api/pdf/generate
          filters:
            - ExtractUsername
        - id: pdf-service
          uri: lb://pdf-service
          predicates:
            - Path=/api/pdf/upload