apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-service
  template:
    metadata:
      labels:
        app: pdf-service
    spec:
      containers:
        - name: app
          image: mateuszuran/pdf-service:1.0.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-service
spec:
  selector:
    app: pdf-service
  ports:
    - port: 80
      targetPort: 9191
  type: LoadBalancer
