server:
  port: 0

spring:
  application:
    name: pdf-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

pdf:
  csv:
    link: https://res.cloudinary.com/dzwnsabwr/raw/upload/v1681720314/user_metadata_j0fuwm.csv