server:
  port: 0

spring:
  application:
    name: card-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/card-service
    driver-class-name: org.postgresql.Driver
    username: mateuszuran
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
